apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- ing.yaml
- sa.yaml
- service.yaml
images:
- name: 768972016120.dkr.ecr.us-west-2.amazonaws.com/yeti
  newTag: e82756e39bd6a5fdd16e10ecbff8512bf9f0652f
