apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- ing.yaml
- sa.yaml
- service.yaml
images:
- name: 768972016120.dkr.ecr.us-west-2.amazonaws.com/yeti
  newTag: d8c31f393824378ec5d7416c3d32e553e4d8280b
