apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- ing.yaml
- sa.yaml
- service.yaml
images:
- name: yeti
  newName: public.ecr.aws/a2k4d8v8/yeti
  newTag: 0.0.2